name: zavolla
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  country_picker: ^2.0.27
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.1.0
  flutter_svg: ^2.0.17
  get: ^4.7.1
  pinput: ^5.0.1
  syncfusion_flutter_charts: ^31.1.22

  intl: any
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin/Cabin-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cabin/Cabin-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cabin/Cabin-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cabin/Cabin-Bold.ttf
          weight: 700

flutter_assets:
  assets_path: assets/images/
  output_path: lib/constants/
  filename: app_images.dart
  field_prefix: ''
